--DDL 복습
--CREATE,ALTER(ADD,MODIFY,DROP)
SELECT * FROM EMP;
CREATE TABLE CHAPPI(
    NAME VARCHAR(10),
    PHONE VARCHAR(10),
    ADDRESS VARCHAR(10));
    
SELECT * FROM CHAPPI;
DROP TABLE CHAPPI;

CREATE TABLE EMP001 AS SELECT * FROM EMP;
SELECT * FROM EMP001;
DESC EMP001;
CREATE TABLE EMP002 AS SELECT * FROM EMP WHERE DEPTNO=10;
SELECT * FROM EMP002;
ALTER TABLE EMP001 ADD(PMGR NUMBER(10));--열 추가
ALTER TABLE EMP001 MODIFY(JOB VARCHAR2(10));--포멧 변경
ALTER TABLE EMP001 DROP COLUMN PMGR;

CREATE TABLE DEPT001 AS SELECT * FROM DEPT;
SELECT * FROM DEPT001;
DESC DEPT001;
DROP TABLE DEPT001;
ALTER TABLE DEPT001 ADD(DEPT NUMBER(10)); --NULL추가됨
ALTER TABLE DEPT001 MODIFY(LOC VARCHAR2(10));
ALTER TABLE DEPT001 DROP COLUMN DEPT;
TRUNCATE TABLE DEPT001;--포멧은 남고 내용만 삭제
SELECT * FROM DEPT001;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--DML
--INSERT INTO(이름) VALUES(값)
SELECT * FROM DEPT01;
--내용 추가
INSERT INTO DEPT01(DEPTNO,DNAME,LOC) VALUES (10,'AI','SEOUL');
INSERT INTO DEPT01(DEPTNO,DNAME,LOC) VALUES (20,'DATE','BUSAN');
INSERT INTO DEPT01(DEPTNO,DNAME,LOC) VALUES (30,'SI','ALLSAN');
INSERT INTO DEPT01 VALUES (40,'ACCOUNT','NEW YORK');

--NULL 값을 삽입하는 방법 <명시적> VALUES에 NULL 입력 <암시적>생략한 칼럼은 NULL
--NOT NULL 제약 조건이 지정된 DEPTNO 컬럼은 널 값을 입력할 수 없다.
DESC DEPT;
INSERT INTO DEPT01(DEPTNO,LOC) VALUES (70,NULL);--암시적,명시적

DROP TABLE SAM01;
CREATE TABLE SAM01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    SAL NUMBER(7,2));
SELECT * FROM SAM01;
INSERT INTO SAM01 VALUES (1000,'APPLE','POLICE',10000);
INSERT INTO SAM01 VALUES (1010,'BANANA','NURSE',15000);
INSERT INTO SAM01 VALUES (1020,'ORANGE','DOCTOR',25000);
INSERT INTO SAM01 VALUES (1030,'VERY','NULL',25000);
INSERT INTO SAM01 VALUES (1040,'CAT','NULL',2000);
INSERT INTO SAM01 VALUES (7782,'CLARK','MANAGER',2450);
INSERT INTO SAM01 VALUES (7839,'KING','PRESIDENT',5000);
INSERT INTO SAM01 VALUES (7934,'MILLER','CLERK',1300);

--서브쿼리로 데이터 삽입하기
DROP TABLE DEPT02;
CREATE TABLE DEPT02 AS SELECT * FROM DEPT WHERE 1=0;
SELECT * FROM DEPT02;
INSERT INTO DEPT02 SELECT * FROM DEPT;

SELECT * FROM BOOK;
DESC BOOK;
INSERT INTO BOOK VALUES(11,'스포츠의학','한솔의학서적',90000,'19/11/01');

--UPDATE~SET~ 테이블에 저장된 데이터를 수정
--어떤 행의 데이터를 수정하는지 WHERE절 활용
--EMP 테이블과 같은 구조와 같은 내용의 테이블 EMP01을 생성,모든 사원의 부서번호를 30번으로 수정
CREATE TABLE EMP01 AS SELECT * FROM EMP;
SELECT * FROM EMP01;
UPDATE EMP01 SET DEPTNO=30;--WHERE 없으니 부서번호 모두 수정됨

--EMP01테이블의 모든 사원의 급여를 10% 인상시키는 UPDATE문
UPDATE EMP01 SET SAL=SAL+(SAL*1/10);
SELECT * FROM EMP01;
--모든 사원의 입사일을 오늘로 수정하는 UPDATE문 작성
UPDATE EMP01 SET HIREDATE=SYSDATE;
SELECT * FROM EMP01;

--부서번호가 10번인 사원의 부서 번호를 30번으로 수정하는 UPDATE문
CREATE TABLE EMP10 AS SELECT * FROM EMP;
SELECT * FROM EMP10;
UPDATE EMP10 SET DEPTNO=30 WHERE DEPTNO=10;

--급여가 3000이상인 사원만 급여를 10%인상
DROP TABLE EMP10;
CREATE TABLE EMP10 AS SELECT * FROM EMP;
SELECT * FROM EMP10;
UPDATE EMP10 SET SAL=SAL+(SAL*1/10) WHERE SAL>=3000;

--EMP01테이블에서 ‘DALLAS’에서 근무하는 직원들의 연봉을 1000인상
DROP TABLE EMP10;
CREATE TABLE EMP10 AS SELECT * FROM EMP;
SELECT * FROM EMP10;
SELECT * FROM EMP;
UPDATE EMP10 SET SAL=SAL+1000 WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS');

--SCOTT사원의 부서번호는 90번으로, 직급은 MANAGER로 한꺼번에 수정
CREATE TABLE EMP10 AS SELECT * FROM EMP;
SELECT * FROM EMP;
UPDATE EMP10 SET DEPTNO=90,JOB='MANAGER' WHERE ENAME='SCOTT';
SELECT * FROM EMP10;

--SCOTT사원의 입사일자를 오늘로, 급여를 50으로 커미션을 400으로 수정
DROP TABLE EMP10;
CREATE TABLE EMP10 AS SELECT * FROM EMP;
SELECT * FROM EMP10;
UPDATE EMP10 SET HIREDATE=SYSDATE,SAL=50,COMM=400 WHERE ENAME='SCOTT';

--서브쿼리 이용한 데이터 수정하기

--20번 부서의 지역명을 40번 부서의 지역명으로
DROP TABLE DEPT02;
CREATE TABLE DEPT02  AS SELECT * FROM DEPT;
SELECT * FROM DEPT02;
UPDATE DEPT02 SET LOC=(SELECT LOC FROM DEPT WHERE DEPTNO=40) WHERE DEPTNO=20;

--20번 부서의 지역명, 부서명을 40번 부서의 지역명, 부서명으로 변경
DROP TABLE DETP02;
CREATE TABLE DEPT02 AS SELECT * FROM DEPT;
SELECT * FROM DEPT02;
UPDATE DEPT02 SET (LOC,DNAME)=(SELECT LOC,DNAME FROM DEPT WHERE DEPTNO=40) WHERE DEPTNO=20;

--SAM02 테이블의 모든 사원의 급여와 입사일을 이름이 KING인 사원의 급여와 입사일로 변경
DROP TABLE SAM02;
CREATE TABLE SAM02 AS SELECT * FROM EMP;
SELECT * FROM SAM02;
SELECT SAL,HIREDATE FROM SAM02 WHERE ENAME='KING';
UPDATE SAM02 SET (SAL,HIREDATE)=(SELECT SAL,HIREDATE FROM SAM02 WHERE ENAME='KING');

--DELETE 사용 DELETE FROM 이름 WHERE 조건
--CF) DROP TABLE_
--모든 행 삭제
DELETE FROM SAM02;--TRUNCATE와 비슷 하지만 FROM 차이!!
TRUNCATE TABLE SAM02;
SELECT * FROM SAM02;

--부서 테이블에서 30번 부서만 삭제
DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT * FROM DEPT;
SELECT * FROM DEPT01;
DESC DEPT01; --NOT NULL 사라짐
DESC DEPT; --NOT NULL 
DELETE FROM DEPT01 WHERE DEPTNO=30;

--위의 SAM01 테이블에서 직급이 정해지지 않은 사원을 삭제하시오.
DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT * FROM EMP; 
SELECT * FROM EMP01;
DELETE FROM EMP01 WHERE COMM IS NULL;
--사원테이블에서 부서명이 SALES인 사원을 모두 삭제
DELETE FROM EMP01 WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');
SELECT * FROM EMP01;
--EMP01 테이블에서 RESEARCH 부서 소속 사원들만 삭제
DELETE FROM EMP01 WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='RESEARCH');  
COMMIT;