--REVIEW
--CREATE,ALTER(ADD,MODIFY,DROP)--DDL
SELECT * FROM DEPT;
--쿼리를 이용한 테이블 생성
CREATE TABLE DEPT10 AS SELECT * FROM DEPT;
SELECT * FROM DEPT10;

CREATE TABLE CUSTOMER(
 NAME VARCHAR2(10),
 TEL VARCHAR2(20),
 EMAIL VARCHAR2(20));
SELECT * FROM CUSTOMER;
DESC CUSTOMER;
ALTER TABLE CUSTOMER ADD(ADDRESS VARCHAR2(20));--열추가
ALTER TABLE CUSTOMER MODIFY(TEL VARCHAR2(30));--포멧변경
ALTER TABLE CUSTOMER DROP COLUMN TEL;

--DML(INSERT INTO VALUES,UPDATE SET)
DROP TABLE CUSTOMER;
INSERT INTO CUSTOMER VALUES ('이건한','010-2239-2762','gun@na.com');
INSERT INTO CUSTOMER VALUES ('이정한','010-2222-3333','g@n.com');
INSERT INTO CUSTOMER VALUES ('이일한','010-1111-3333','g11@n.com');
DELETE FROM CUSTOMER WHERE NAME='이건한';
UPDATE CUSTOMER SET NAME='이건한' WHERE NAME='이정한';
SELECT * FROM CUSTOMER;

--sequence
--순차적인 번호를 자동으로 생성하는 객체로 테이블과 독립적으로 생성 및 저장
--시퀀스에서 생성되는 번호는 유일하기 때문에 기본 테이블에서 primary key 생성시 주로 사용
--시퀀스는 테이블과 관계없이 생성,저장,오라클 내부 루틴에 의해 발새애
--문법 순차번호 생성기, 대부분 인위적인 PK 사용 용도
--CREATE SEQUENCE sequence_name 
--[INCREMENT BY n]  [START WITH n] 
--[MAXVALUE n] [MINVALUE n]
--[CYCLE | NOCYCLE] CYCLE 설정시 최대값에 도달하면 최소값부터 다시 시작 NOCYCLE 설정시 최대값 생성 시 시퀀스 생성중지
--[CACHE n | NOCACHE];CACHE 설정시 메모리에 시퀀스 값을 미리 할당하고 NOCACHE 설정시 시퀀스값을 메로리에 할당하지 않음

CREATE TABLE FRIENDS(
    ID NUMBER CONSTRAINT ORDERNO PRIMARY KEY,
    NAME VARCHAR2(10) NOT NULL,
    TEL VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(100),
    LAST_MODIFIED DATE DEFAULT SYSDATE);
SELECT * FROM FRIENDS;
CREATE SEQUENCE FRIENDS_NO INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE;
INSERT INTO FRIENDS (ID,NAME,TEL) VALUES (FRIENDS_NO.NEXTVAL,'홍길동','010-2222-3333');
INSERT INTO FRIENDS (ID,NAME,TEL) VALUES (FRIENDS_NO.NEXTVAL,'이건한','010-2222-2222');
INSERT INTO FRIENDS (ID,NAME,TEL) VALUES (FRIENDS_NO.NEXTVAL,'이정한','010-2222-1111');
INSERT INTO FRIENDS (ID,NAME,TEL) VALUES (FRIENDS_NO.NEXTVAL,'이일용','010-2239-2222');
DROP TABLE FRIENDS;
INSERT INTO FRIENDS VALUES (FRIENDS_NO.NEXTVAL,'이주한','010-9999-2222',NULL,TO_DATE('20201231','YYYYMMDD'));
SELECT * FROM FRIENDS;
SELECT FRIENDS_NO.CURRVAL FROM DUAL;--시퀀스 현재값
-------------------------------------------------------------------------------------
CREATE TABLE CHAPP(
 ID NUMBER CONSTRAINT ORDERNUM PRIMARY KEY,
 NAME VARCHAR2(20),
 TEL VARCHAR2(20) UNIQUE,
 ADDRESS VARCHAR2(20) NOT NULL,
 BIRTHDAY DATE DEFAULT SYSDATE);
 DROP TABLE CHAPP;

 SELECT * FROM CHAPP;
 CREATE SEQUENCE CHAPP_NO INCREMENT BY 2 START WITH 1 MAXVALUE 999 NOCACHE;
 INSERT INTO CHAPP VALUES (CHAPP_NO.NEXTVAL,'이건한','010-2223-4444','서울시 성북구',TO_DATE('19930913','YYYYMMDD'));
INSERT INTO CHAPP VALUES (CHAPP_NO.NEXTVAL,'이정한','010-1111-4444','서울시 성북구',NULL);
--시퀀스 현재값
SELECT CHAPP_NO.CURRVAL FROM DUAL;
-------------------------------------------------------------------------------------
--시퀀스 삭제
DROP SEQUENCE CHAPP_NO;
--시퀀스 수정
ALTER SEQUENCE CHAPP_NO INCREMENT BY 3 MAXVALUE 10 NOCACHE;
INSERT INTO CHAPP(ID,NAME,TEL,ADDRESS) VALUES (CHAPP_NO.NEXTVAL,'이일용','010-1111-3333','서울시 성북구');
INSERT INTO CHAPP(ID,NAME,TEL,ADDRESS) VALUES (CHAPP_NO.NEXTVAL,'이일한','010-2222-3333','서울시 성북구');

--practice
SELECT * FROM CUSTOMER;
DROP TABLE CUSTOMER;
--DDL(CREATE,ALTER(ADD,MODIFY,DROP)
--DML(INSERT INTO VALUES,UPDATE SET)
--SEQUENCE
DROP TABLE CUS_LEVEL;
CREATE TABLE CUS_LEVEL(
LEVELNO NUMBER(10) PRIMARY KEY,
LEVELNAME VARCHAR2(20) NOT NULL);

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
CNO NUMBER(10) PRIMARY KEY,
CNAME VARCHAR2(10) NOT NULL,
JOINDATE DATE DEFAULT SYSDATE,
PHONE VARCHAR2(20) UNIQUE,
POINT NUMBER(10),
LEVELNO NUMBER(10)REFERENCES CUS_LEVEL(LEVELNO));

DROP SEQUENCE CUSTOMER_NO;
CREATE SEQUENCE CUSTOMER_NO INCREMENT BY 1 START WITH 1 MAXVALUE 99 NOCACHE;

INSERT INTO CUS_LEVEL VALUES (1,'VVIP');
INSERT INTO CUS_LEVEL VALUES (2,'VIP');
INSERT INTO CUS_LEVEL VALUES (3,'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4,'BLACK');
SELECT * FROM CUS_LEVEL;
SELECT * FROM CUSTOMER;
INSERT INTO CUSTOMER(CNO,CNAME,PHONE,POINT,LEVELNO) VALUES (CUSTOMER_NO.NEXTVAL,'홍길동','010-9999-9999',0,1);
INSERT INTO CUSTOMER VALUES (CUSTOMER_NO.NEXTVAL,'이철수',TO_DATE('20200610','YY/MM/DD'),'010-8888-8888',NULL,2);

SELECT * FROM CUSTOMER;
SELECT * FROM CUS_LEVEL;
UPDATE CUSTOMER SET POINT=300 WHERE POINT=0;
--EQUAL JOIN
SELECT CNO,CNAME,JOINDATE,PHONE,POINT,LEVELNAME FROM CUSTOMER C,CUS_LEVEL D WHERE C.LEVELNO=D.LEVELNO;

--FINAL
ALTER TABLE CUSTOMER DROP COLUMN CNO;
ALTER TABLE CUSTOMER ADD (CNO NUMBER(10));
ALTER TABLE CUSTOMER MODIFY(CNO NUMBER(20));
UPDATE CUSTOMER SET CNO=1 WHERE POINT=300;
UPDATE CUSTOMER SET CNO=2 WHERE LEVELNO=2;