SELECT * FROM EMP;
SELECT ENAME,SAL FROM EMP WHERE SAL BETWEEN 1000 AND 2000;
SELECT ENAME,SAL FROM EMP WHERE SAL NOT BETWEEN 1000 AND 2000;
SELECT EMPNO,ENAME,JOB,SAL,HIREDATE FROM EMP WHERE EMPNO IN (7902,7934);
SELECT EMPNO,ENAME,JOB,SAL,HIREDATE FROM EMP WHERE SAL IN (3500,3000);
SELECT EMPNO,ENAME,JOB,SAL,HIREDATE FROM EMP WHERE SAL IN (200,100);
-----------------------------------------------------------------------
-- 2.LIKE
SELECT ENAME,MGR,SAL FROM EMP;
SELECT ENAME,MGR,SAL FROM EMP WHERE ENAME LIKE 'M%'; --처음에 엠으로 시작할때
SELECT ENAME,MGR,SAL FROM EMP WHERE ENAME LIKE '%M%'; --중간에 엠있을때
SELECT ENAME,MGR,SAL FROM EMP WHERE ENAME LIKE '%S'; --끝에 S가 있을 때
SELECT ENAME,MGR FROM EMP WHERE ENAME LIKE '_L%'; --두번째로 엘이 있을때

--EMP 테이블에서 hiredate가 1982년인 사원의 empno,ename,job,sal,hiredate,deptno 를 출력하시오
SELECT EMPNO,ENAME,JOB,SAL,HIREDATE,DEPTNO FROM EMP 
                                WHERE HIREDATE BETWEEN '82/01/01' AND '82/12/31';
SELECT EMPNO,ENAME,JOB,SAL,HIREDATE,DEPTNO FROM EMP WHERE HIREDATE LIKE '82%';
SELECT EMPNO,ENAME,JOB,SAL,HIREDATE,DEPTNO FROM EMP WHERE HIREDATE LIKE '___12%';
SELECT EMPNO,ENAME,JOB,SAL,HIREDATE,DEPTNO FROM EMP 
                                WHERE HIREDATE>=TO_DATE('1982/01/01','yyyy/mm/dd') AND
                                HIREDATE<=TO_DATE('1982/12/31','yyyy/mm/dd');
                                
-- EMP 테이블에서 입사일이 1월인 사원의 EMPNO, ENAME, JOB, SAL, HIREDATE을 출력하시오
SELECT EMPNO,ENAME,JOB,SAL,HIREDATE FROM EMP WHERE HIREDATE LIKE '___01%';
SELECT EMPNO,ENAME,JOB,SAL,HIREDATE FROM EMP WHERE HIREDATE LIKE '__/01/__';

--IN 연습
SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO IN (10,30);
SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO NOT IN (10,30);
SELECT * FROM EMP;
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP WHERE JOB IN ('CLERK','ANALYST');
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP WHERE JOB NOT IN ('CLERK','ANALYST');

--ODER BY 연습
SELECT ENAME,EMPNO,JOB,HIREDATE FROM EMP ORDER BY HIREDATE;
SELECT ENAME,EMPNO,JOB FROM EMP ORDER BY EMPNO DESC; --내림차순
SELECT ENAME,EMPNO,JOB FROM EMP ORDER BY EMPNO; --오름차순
SELECT * FROM EMP;
SELECT * FROM EMP ORDER BY SAL;
SELECT ENAME,SAL FROM EMP ORDER BY SAL DESC;

--연봉이 작은 것부터 순서대로 출력(연봉이 같으면 입사일로 나중인 사람 순으로 정함)
SELECT * FROM EMP ORDER BY SAL,HIREDATE DESC; --내림차순
--% 연습
SELECT ENAME,EMPNO,JOB FROM EMP WHERE ENAME LIKE '%K';
SELECT ENAME,EMPNO,JOB FROM EMP WHERE ENAME LIKE 'K%';

--1.EMP 테이블에서 sal이 3000이상인 사원의 empno, ename, job, sal을 출력
SELECT EMPNO,ENAME,JOB,SAL FROM EMP WHERE SAL>3000;
--2.EMP 테이블에서 empno가 7788인 사원의 ename과 deptno를 출력
SELECT ENAME,DEPTNO FROM EMP WHERE EMPNO=7788;
--3.연봉(SAL*12+COMM)이 24000이상인 사번, 이름, 급여 출력 (급여순정렬)
SELECT EMPNO,ENAME,SAL,SAL*12+NVL(COMM,0) 연봉 FROM EMP 
                                    WHERE SAL*12+NVL(COMM,0)>24000 ORDER BY 연봉;
--4.EMP 테이블에서 hiredate가 1981년 2월 20과 1981년 5월 1일 사이에 입사한 사원의 
--ename,job,hiredate을 출력하는 SELECT 문장을 작성 (단 hiredate 순으로 출력)
SELECT ENAME,JOB,HIREDATE 입사일 FROM EMP 
                    WHERE HIREDATE BETWEEN '81/02/20' AND '81/05/01' ORDER BY 입사일 DESC;
--5.EMP 테이블에서 deptno가 10,20인 사원의 모든 정보를 출력 (단 ename순으로 정렬)
SELECT * FROM EMP WHERE DEPTNO IN (10,20) ORDER BY ENAME;
SELECT * FROM EMP WHERE DEPTNO=10 OR DEPTNO=20 ORDER BY ENAME;
--6.EMP 테이블에서 sal이 1500이상이고 deptno가 10,30인 사원의 ename과 sal를 출력
-- (단 TITLE을 employee과 Monthly Salary로 출력)
SELECT ENAME 고용주 ,SAL 월급 FROM EMP WHERE SAL>1500 AND DEPTNO IN (10,30);
--7.EMP 테이블에서 hiredate가 1982년인 사원의 모든 정보를 출력
SELECT * FROM EMP WHERE HIREDATE LIKE '82%' ORDER BY HIREDATE;

--8.이름의 첫자가 C부터  P로 시작하는 사람의 이름, 급여 이름순 정렬
SELECT * FROM EMP;
SELECT ENAME,SAL FROM EMP WHERE ENAME LIKE 'C%';
SELECT ENAME,SAL FROM EMP WHERE ENAME BETWEEN 'B' AND 'C'; --뒤에 포함 안됨
SELECT ENAME,SAL FROM EMP WHERE ENAME BETWEEN 'C' AND 'Q';

--9.EMP 테이블에서 comm이 sal보다 10%가 많은 모든 사원에 대하여 이름, 급여, 상여금을 
--출력하는 SELECT 문을 작성 
SELECT ENAME,SAL,COMM FROM EMP WHERE COMM>SAL*0.1;

--10.EMP 테이블에서 job이 CLERK이거나 ANALYST이고 sal이 1000,3000,5000이 아닌 모든 사원의 정보를 출력
SELECT * FROM EMP WHERE JOB='CLERK' OR JOB='ANALYST' AND SAL NOT IN (1000,3000,5000);

--11.EMP 테이블에서 ename에 L이 두 자가 있고 deptno가 30이거나 또는 mgr이 7782인 사원의 
--모든 정보를 출력하는 SELECT 문을 작성하여라.
SELECT * FROM EMP WHERE ENAME LIKE '%LL%';
SELECT * FROM EMP WHERE ENAME LIKE '%L%';
--12.사원 테이블에서 입사일이 81년도인 직원의 사번,사원명, 입사일, 업무, 급여를 출력
SELECT EMPNO,ENAME,HIREDATE,JOB,SAL FROM EMP WHERE HIREDATE LIKE '81%';
--13.사원 테이블에서 입사일이81년이고 업무가 'SALESMAN'이 아닌 직원의 사번, 사원명, 입사일, 
-- 업무, 급여를 검색하시오.
SELECT EMPNO,ENAME,HIREDATE,JOB,SAL FROM EMP WHERE HIREDATE LIKE '81%' AND JOB='SALESMAN';
SELECT EMPNO,ENAME,HIREDATE,JOB,SAL FROM EMP WHERE HIREDATE LIKE '81%' AND JOB!='SALESMAN';
--14.사원 테이블의 사번, 사원명, 입사일, 업무, 급여를 급여가 높은 순으로 정렬하고, 
-- 급여가 같으면 입사일이 빠른 사원으로 정렬하시오.
SELECT EMPNO,ENAME,HIREDATE,JOB,SAL FROM EMP ORDER BY SAL DESC,HIREDATE ASC;

--15.사원 테이블에서 사원명의 세 번째 알파벳이 'N'인 사원의 사번, 사원명을 검색하시오
SELECT EMPNO,ENAME FROM EMP WHERE ENAME LIKE '__N%';
--16.사원 테이블에서연봉(SAL*12)이 35000 이상인 사번, 사원명, 연봉을 검색 하시오.
SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL*12>35000;