-- 1.SELECT
SELECT * FROM EMP;
DESC EMP;
SELECT * FROM TAB;
SELECT * FROM EMP;
SELECT EMPNO 번호,ENAME 이름,JOB 직업 FROM EMP;
SELECT ENAME 이름,SAL 연봉,COMM 상여금,MGR 상사,HIREDATE 입사일 FROM EMP;
--81년도,82년도,83년도
SELECT ENAME,SAL,HIREDATE 입사일 FROM EMP ORDER BY 입사일;
SELECT ENAME,SAL 연봉,HIREDATE 입사일 FROM EMP ORDER BY 연봉,입사일;
SELECT * FROM EMP;
--연봉
SELECT ENAME,JOB,SAL,COMM,SAL*12+NVL(COMM,0) 연봉 FROM EMP ORDER BY 연봉;
--부서 10번
SELECT * FROM EMP WHERE DEPTNO=10;
--SAL>=3000
SELECT * FROM EMP WHERE SAL>=3000;
--입사일이 82년도인경우
SELECT * FROM EMP WHERE HIREDATE BETWEEN '82/01/01' AND '82/12/31';
--입사일이 82년도인 경우
SELECT * FROM EMP WHERE HIREDATE LIKE '82%' ORDER BY HIREDATE;
--날짜 셋팅 변경
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/YYYY';
SELECT * FROM EMP;
ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';
SELECT * FROM EMP;
-- 문자형를 날짜형으로 변환 : TO_DATE('81/02/20', 'RR/MM/DD')
-- 날짜형을 문자형으로 변환 : TO_CHAR(날짜형, 패턴)
DESC EMP;
--LL이 이름에 있는경우
SELECT * FROM EMP WHERE ENAME LIKE '%L%L%' AND DEPTNO=30;
--IN 활용
SELECT * FROM EMP;
SELECT * FROM EMP WHERE JOB IN ('CLERK','MANAGER');
SELECT * FROM EMP WHERE DEPTNO IN (10,20);
--82년도
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'YYYY')=1982;
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'RR')=82;
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'YYYY')=1982;
--12월달
SELECT * FROM EMP WHERE HIREDATE LIKE '__/12/__';
SELECT * FROM EMP WHERE HIREDATE LIKE '___12%';
--17일
SELECT * FROM EMP WHERE HIREDATE LIKE '__/__/17';
SELECT * FROM EMP WHERE HIREDATE LIKE '%17';