-- CROSS JOIN:두개의 컬럼 합치기
--	Equi Join : 동일한 컬럼을 기준으로 조인 DEPTNO
­-	Non-Equi Join : 동일한 컬럼없이 다른 조건을 사용하여 조인 GRADE
­-	Outer Join : 조인 조건에 만족하지 않는 행도 나타나는 조인
­-	Self Join : 한 테이블 내에서 조인.

--SELF JOIN 
--SMITH의 매니저 >>FORD
SELECT * FROM EMP;
SELECT MGR FROM EMP WHERE ENAME='SMITH';
SELECT ENAME FROM EMP WHERE EMPNO=7902;
SELECT M.ENAME FROM EMP W,EMP M WHERE W.MGR=M.EMPNO AND W.ENAME='SMITH';

--WARD의 매니저>>BLAKE
SELECT M.ENAME FROM EMP W,EMP M WHERE W.MGR=M.EMPNO AND W.ENAME='WARD';
--킹의 매니저 --NULL
SELECT M.ENAME FROM EMP W,EMP M WHERE W.MGR=M.EMPNO AND W.ENAME='KING';

--매니저가 킹인 사원들의 이름과 직급을 출력하세요
SELECT EMPNO FROM EMP WHERE ENAME='KING';
SELECT ENAME,JOB FROM EMP WHERE MGR=7839;
SELECT W.ENAME,W.JOB FROM EMP W,EMP M WHERE W.MGR=M.EMPNO AND M.ENAME='KING';

--SCOTT과 동일한 부서번호에서 근무하는 사원의 이름을 출력하시오
SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT';
SELECT ENAME FROM EMP WHERE DEPTNO=20;
SELECT W2.ENAME FROM EMP W1,EMP W2 WHERE W1.DEPTNO=W2.DEPTNO AND W1.ENAME='SCOTT'; 

­-SCOTT W2과 동일한 근무지에서 근무하는 사원W1의 이름을 출력하시오(2단계 최종문제)
SELECT LOC FROM DEPT D,EMP E WHERE E.DEPTNO=D.DEPTNO AND ENAME='SCOTT';
SELECT ENAME FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO AND LOC='DALLAS';

SELECT W1.ENAME FROM EMP W1,EMP W2,DEPT D1,DEPT D2 WHERE D1.LOC=D2.LOC AND W1.DEPTNO=D1.DEPTNO
                                          AND W2.DEPTNO=D2.DEPTNO AND W2.ENAME='SCOTT';
--OUTER JOIN 조인 조건에 만족하지 못해도 해당 열을 표시하고 싶을때 사용
--SELF JOIN
SELECT * FROM EMP;
--킹의 매니저의 이름
SELECT W.ENAME,M.ENAME FROM EMP W,EMP M WHERE W.MGR=M.EMPNO;
SELECT W.ENAME,M.ENAME FROM EMP W,EMP M WHERE W.MGR=M.EMPNO(+);
SELECT M.ENAME FROM EMP W,EMP M WHERE W.MGR=M.EMPNO(+) AND W.ENAME='KING';>>NULL 표시
SELECT M.ENAME FROM EMP W,EMP M WHERE W.MGR=M.EMPNO AND W.ENAME='SMITH';
--말단사원 리스트
SELECT W.ENAME,M.ENAME FROM EMP W,EMP M WHERE W.MGR=M.EMPNO;
SELECT W.ENAME,M.ENAME FROM EMP W,EMP M WHERE W.MGR(+)=M.EMPNO;
--이름 업무 부서명
SELECT * FROM DEPT;
SELECT ENAME,JOB,DNAME FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO;
--이름 업무 부서명(직원 없는)
SELECT ENAME,JOB,DNAME FROM EMP E,DEPT D WHERE E.DEPTNO(+)=D.DEPTNO;
SELECT ENAME,JOB,DNAME,SAL FROM EMP E,DEPT D WHERE E.DEPTNO(+)=D.DEPTNO ORDER BY DNAME,SAL DESC;
--FORD의 매니저는 JONES입니다.
SELECT M.ENAME FROM EMP W,EMP M WHERE W.MGR=M.EMPNO AND W.ENAME='FORD';