--REVIEW
SELECT * FROM EMP;
SELECT * FROM EMP;
SELECT ENAME,SAL FROM EMP;
SELECT ENAME,SAL FROM EMP;
SELECT ENAME,RPAD(SUBSTR(SAL,1,1),LENGTH(SAL),'#') FROM EMP;
SELECT ENAME,RPAD(SUBSTR(SAL,1,1),LENGTH(SAL),'#') FROM EMP;
SELECT ENAME,RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'#') FROM EMP;
SELECT INITCAP(ENAME),LOWER(ENAME) FROM EMP;
SELECT INITCAP(ENAME),LOWER(ENAME) FROM EMP;
SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE LIKE '82%';
SELECT ENAME,HIREDATE FROM EMP;
SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE LIKE '82%';
SELECT ENAME,HIREDATE FROM EMP WHERE TO_CHAR(HIREDATE,'YYYY')='1982';
SELECT ENAME,HIREDATE FROM EMP WHERE SUBSTR(HIREDATE,1,2)='82';
SELECT ENAME,HIREDATE FROM EMP WHERE SUBSTR(HIREDATE,1,2)='82';
SELECT INSTR('ABCABCABC','A') FROM DUAL; --1
SELECT INSTR('ABCABCABC','A',2) FROM DUAL; --4
SELECT INSTR('ABCABCABC','A',5) FROM DUAL; --7
SELECT INSTR('ABCABCABC','A',3,1) FROM DUAL; --4
SELECT INSTR('ABCABCABC','A',3,2) FROM DUAL; --7
SELECT INSTR('ABABABAB','A') FROM DUAL;
SELECT INSTR('ABABABAB','A',2) FROM DUAL;
SELECT INSTR('ABABABAB','A',2,3) FROM DUAL;
SELECT CONCAT(ENAME,SAL) FROM EMP;

--3.날짜 함수----------------------------------------------------
----------------------------------------------------------------
--SYSDATE(현재 날짜),MONTHS_BETWEEN 두 날짜 사이 개월수,ADD_MONTHS 특정날짜에 개월수 더한다
SELECT SYSDATE FROM DUAL;
--NEXT_DAY 특정 날짜에서 최초로 도래하는 인자로 받은 요일의 날짜를 변환
--LAST_DAY 해당 달의 마지막 날짜를 반환한다.
--ROUND 받은 날짜를 특정 기준으로 반올림
--TRUNC 받은 날짜를 특정 기준으로 버린다.

--EXAMPLE)
SELECT SYSDATE FROM DUAL;
SELECT SYSDATE-1 어제,SYSDATE 오늘,SYSDATE+1 내일 FROM DUAL;
SELECT TO_CHAR(SYSDATE-1,'YY-MM-DD DY HH24:MI:SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YY-MM-DD DY HH24:MI:SS') FROM DUAL;
SELECT SYSDATE,SYSDATE+14 반납일 FROM DUAL;

--MONTH_BETWEEN 활용
SELECT ENAME,SYSDATE,HIREDATE,MONTHS_BETWEEN(SYSDATE,HIREDATE) FROM EMP;
SELECT ENAME,SYSDATE,HIREDATE,MONTHS_BETWEEN(SYSDATE,HIREDATE) FROM EMP;
SELECT ENAME,SYSDATE,HIREDATE,TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)) FROM EMP; --버림
SELECT ENAME,SYSDATE,HIREDATE,TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)) FROM EMP;
SELECT ENAME,SYSDATE,HIREDATE,ROUND(MONTHS_BETWEEN(SYSDATE,HIREDATE)) FROM EMP; --첫째자리에서 올림

--몇개월 뒤에 ADD_MONTHS
SELECT ADD_MONTHS(SYSDATE,2) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE,2) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE,12) FROM DUAL;

--NEXT_DAY 제일 가까운 요일
SELECT SYSDATE,NEXT_DAY(SYSDATE,'수요일') FROM DUAL; --제일 가까운 요일
SELECT SYSDATE,NEXT_DAY(SYSDATE,'금요일') FROM DUAL;

--LAST_DAY 마지막 일
SELECT SYSDATE,LAST_DAY(SYSDATE) FROM DUAL;
--MONTH는 16일 기준으로 반올림/해당 월의 1일로 변환
SELECT HIREDATE,ROUND(HIREDATE,'MONTH'),TRUNC(HIREDATE,'MONTH') FROM EMP;
--YEAR는 6개월 기준으로 반올림/해당 연도의 1월 1일로 변환
SELECT HIREDATE,ROUND(HIREDATE,'YEAR'),TRUNC(HIREDATE,'YEAR'),
                            NEXT_DAY(HIREDATE,'일요일'),ROUND(HIREDATE,'DAY') FROM EMP;
--DAY는 가까운 일요일 기준으로 반올림
SELECT SYSDATE,ROUND(SYSDATE,'DAY'),TRUNC(SYSDATE,'DAY') FROM DUAL;
SELECT SYSDATE,ROUND(SYSDATE+5,'DAY'),TRUNC(SYSDATE+5,'DAY') FROM DUAL;
--사원들의 현재까지 근무일수
SELECT ENAME,TRUNC(SYSDATE-HIREDATE) FROM EMP;
--월급날이 말일인 경우
SELECT HIREDATE,LAST_DAY(HIREDATE) FROM EMP;

--월급날이 1일인경우(16일 이후엔 다음달 1일/15일 이전은 그 달 1일
SELECT HIREDATE,ROUND(HIREDATE,'MONTH')  FROM EMP; --월급날이 1일(전 달이 포함되서 안됨)
SELECT HIREDATE,ROUND(HIREDATE+15,'MONTH') FROM EMP; --월급날이 1일
--월급날이 2일 경우 
SELECT HIREDATE,ROUND(HIREDATE,'MONTH')+1 FROM EMP;
SELECT HIREDATE,ROUND(HIREDATE+15,'MONTH')+1 FROM EMP;
SELECT HIREDATE,ROUND(HIREDATE+14,'MONTH')+1 FROM EMP;--5월 1일입사일이 5월 2일에 월급
--월급날 3일 경우
SELECT HIREDATE,ROUND(HIREDATE+13,'MONTH')+2 FROM EMP;
--월급날 14일 경우
SELECT HIREDATE,ROUND(HIREDATE+2,'MONTH')+13 FROM EMP;--5월 13일 입사일이 5월 14일에 월급
--월급날 15일 경우
SELECT HIREDATE,ROUND(HIREDATE+1,'MONTH')+14 FROM EMP;--5월 14일 입사일이 5월 15일에 월급
--월급날 16일 경우
SELECT HIREDATE,ROUND(HIREDATE,'MONTH')+15 FROM EMP;
--월급날 17일 경우
SELECT HIREDATE,ROUND(HIREDATE-1,'MONTH')+16 FROM EMP;---6월 16일이면  6월 17일에 월급
--월급날 28일 경우
SELECT HIREDATE,ROUND(HIREDATE-12,'MONTH')+27 FROM EMP; --6월 27일이면 6월 28일에 월급

--무조건 그 달의 1일로
SELECT HIREDATE,TRUNC(HIREDATE,'MONTH') FROM EMP; --2일~15일 친구들은 오류가 생김
--ROUND와 비교
SELECT HIREDATE,ROUND(HIREDATE+15,'MONTH') FROM EMP;
--
SELECT ENAME,SYSDATE,HIREDATE,MONTHS_BETWEEN(SYSDATE,HIREDATE) FROM EMP;
SELECT ENAME,SYSDATE,HIREDATE,TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)) FROM EMP;
SELECT ENAME,HIREDATE,ADD_MONTHS(HIREDATE,6) FROM EMP;
SELECT HIREDATE,LAST_DAY(HIREDATE) FROM EMP;

-------------------------------------------------------------------------
----------------------4.형변환 함수----------------------------------------
-------------------------------------------------------------------------
--숫자,문자,날짜의 데이터 형을 다른 데이터형으로 변환해주는 함수
--1.TO_CHAR>>날짜형을 혹은 숫자형을 문자형으로 변환
SELECT SYSDATE,TO_CHAR(SYSDATE,'YYYY-MM-DD') FROM DUAL;
SELECT HIREDATE,TO_CHAR(HIREDATE,'YYYY/MM/DD DAY') FROM EMP;
SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD,HH24:MI:SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD DY AM HH:MI:SS') FROM DUAL;

--TO_CHAR(숫자 데이터,출력형식)
--L:각 지역별 통화 기호,0:자릿수를 나타내며 맞지않을경우 0으로 채움,9:자릿수를 나타내며 맞지 않을 경우 안 채운다
SELECT ENAME,SAL,TO_CHAR(SAL,'L999,999') FROM EMP;
SELECT TO_CHAR(123456,'000000000') FROM DUAL; --000123456
SELECT TO_CHAR(123456,'L99,999,999') FROM DUAL; --123,456
SELECT TO_CHAR(12345678,'L99,999,999') FROM DUAL;

--TO_DATE(문자형을 날짜형으로)
SELECT HIREDATE FROM EMP;
SELECT HIREDATE FROM EMP WHERE HIREDATE=TO_DATE('19801217','YYYY/MM/DD');
SELECT HIREDATE FROM EMP WHERE HIREDATE=TO_DATE('19811117','YYYY-MM-DD');
SELECT TRUNC(SYSDATE-TO_DATE('19930913','YYYY-MM-DD')) FROM DUAL; --10288일
SELECT TRUNC(SYSDATE-TRUNC(SYSDATE,'YEAR')) FROM DUAL; --316일
SELECT TRUNC(SYSDATE,'YEAR') FROM DUAL;

--TO_NUMBER 문자형을 숫자형으로
SELECT TO_NUMBER('20,000','99,999')-TO_NUMBER('10,000','99,999') FROM DUAL;

--NVL 함수>>NULL을 다른 값으로 변환하나는 NVL 함수
SELECT ENAME,SAL,COMM FROM EMP;
SELECT ENAME,SAL,NVL(COMM,0) FROM EMP;
SELECT ENAME,SAL,COMM,SAL*12+NVL(COMM,0)연봉 FROM EMP ORDER BY 연봉,SAL;
SELECT ENAME,MGR FROM EMP;
SELECT EMPNO,ENAME,NVL(MGR,9999) FROM EMP WHERE MGR IS NULL;
--SELECT EMPNO,ENAME,NVL(MGR,'CEO') FROM EMP WHERE MGR IS NULL;
SELECT EMPNO,ENAME,MGR FROM EMP;
SELECT W.EMPNO,W.ENAME,NVL(M.ENAME,'CEO') FROM EMP W,EMP M
                                        WHERE W.MGR=M.EMPNO;
--SELF JOIN 필요
SELECT W.EMPNO,W.ENAME,NVL(M.ENAME,'CEO') FROM EMP W,EMP M
                                        WHERE W.MGR=M.EMPNO(+) AND W.MGR IS NULL;
SELECT * FROM EMP;
SELECT W.ENAME 직원,M.ENAME 매니저 FROM EMP W,EMP M WHERE W.MGR=M.EMPNO(+);

--그 외의 함수들
SELECT EMPNO,ENAME,JOB,SAL,TO_CHAR(SAL,'$999,999') FROM EMP WHERE DEPTNO=20;
--EXTRACT 활용
SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;
SELECT ENAME,HIREDATE,EXTRACT(MONTH FROM HIREDATE) FROM EMP;
SELECT ENAME,HIREDATE,EXTRACT(DAY FROM HIREDATE) FROM EMP;
--사원 테이블의 계층화
--LEVEL : 계층적 질의문에서 검색된 결과에 대한 계층별로 레벨 표시
--START WITH : 계층적인 출력 형식을 표현하기 위한 최상위 행
--CONNECT BY PRIOR : 계층 관계의 데이터를 지정하는 컬럼

SELECT LPAD('  ', 3*LEVEL-3)|| ENAME, LEVEL, EMPNO, MGR, DEPTNO FROM EMP START WITH MGR IS NULL CONNECT BY PRIOR 
EMPNO=MGR;
SELECT LPAD('  ', 3*LEVEL-3)|| ENAME, LEVEL, EMPNO, MGR, DEPTNO 
FROM EMP START WITH ENAME='KING' CONNECT BY PRIOR EMPNO=MGR;
SELECT LPAD('  ', 3*LEVEL-3)|| ENAME, LEVEL, EMPNO, MGR, DEPTNO 
FROM EMP WHERE ENAME!='FORD' START WITH ENAME='KING' CONNECT BY PRIOR EMPNO=MGR;

--82년도 입사일 직원
SELECT ENAME,HIREDATE FROM EMP;
SELECT ENAME,HIREDATE FROM EMP WHERE EXTRACT(YEAR FROM HIREDATE)=1982;
SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE LIKE '82%';
SELECT ENAME,HIREDATE FROM EMP WHERE SUBSTR(HIREDATE,1,2)=82;
SELECT ENAME,HIREDATE FROM EMP WHERE TO_CHAR(HIREDATE,'YYYY')=1982;
SELECT TO_DATE(19930913,'YYYY/MM/DD') FROM DUAL;
SELECT TO_CHAR(12345,'L999,999') FROM DUAL;--빈자리 표시 안됨
SELECT TO_CHAR(12345,'000000') FROM DUAL; --빈자리 0으로 표시
SELECT SAL,TO_CHAR(SAL,'L99,99') FROM EMP;

-- <총 연습문제>
-- 1. 현재 날짜를 출력하고 TITLE에 “Current Date”로 출력하는 SELECT 문장을 기술하시오.
SELECT SYSDATE "현재 날짜" FROM DUAL;
-- 2. EMP 테이블에서 현재 급여에 15%가 증가된 급여를 계산하여,
-- 사원번호,이름,업무,급여,증가된 급여(New Salary),증가액(Increase)를 출력하는 SELECT 문장
SELECT EMPNO 번호,ENAME 이름 ,JOB 직업,SAL 연봉,SAL+(SAL*15/100) 증가액 FROM EMP;
--3. 이름, 입사일, 입사일로부터 6개월 후 돌아오는 월요일 구하여 출력하는 SELECT 문장을 기술하시오.
SELECT ENAME,HIREDATE,ADD_MONTHS(HIREDATE,6) FROM EMP;
SELECT ENAME,HIREDATE,ADD_MONTHS(HIREDATE,6),NEXT_DAY(ADD_MONTHS(HIREDATE,6),'월요일') FROM EMP;
--4. 이름, 입사일, 입사일로부터 현재까지의 개월수, 급여, 입사일부터 현재까지의 받은 급여의 총계를 출력
SELECT ENAME,HIREDATE,TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)),SAL,SAL*TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE))
                                                            FROM EMP;
--5. 모든 사원의 이름과 급여(15자리로 출력 좌측의 빈 곳은 “*”로 대치)를 출력
SELECT ENAME,SAL FROM EMP;
SELECT ENAME,LPAD(SAL,15,'*') FROM EMP;
--6. 모든 사원의 정보를 이름,업무,입사일,입사한 요일을 출력하는 SELECT 문장을 기술하시오.
SELECT ENAME,JOB,HIREDATE FROM EMP;
SELECT ENAME,JOB,TO_CHAR(HIREDATE,'DAY') FROM EMP;
--7. 이름의 길이가 6자 이상인 사원의 정보를 이름,이름의 글자수,업무를 출력
SELECT ENAME FROM EMP;
SELECT ENAME,LENGTH(ENAME),JOB FROM EMP WHERE LENGTH(ENAME)>=6;
--8. 모든 사원의 정보를 이름, 업무, 급여, 보너스, 급여+보너스를 출력
SELECT ENAME,JOB,SAL,NVL(COMM,0),SAL+NVL(COMM,0) FROM EMP;
-- 9.사원 테이블의 사원명에서 2번째 문자부터 3개의 문자를 추출하시오. 
SELECT ENAME,SUBSTR(ENAME,2,3) FROM EMP; --2번쨰 문자부터 3개 출력
--10. 사원 테이블에서 입사일이 12월인 사원의 사번, 사원명, 입사일을 검색하시오. 
--  시스템에 따라 DATEFORMAT 다를 수 있으므로 아래의 방법도 알아보자
SELECT EMPNO,ENAME,HIREDATE FROM EMP;
SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE TO_CHAR(HIREDATE,'MM')=12;
SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE EXTRACT(MONTH FROM HIREDATE)=12;
--SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE HIREDATE LIKE '%12%'; --일도 포함됨
SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE HIREDATE LIKE '__%12%__';
SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE SUBSTR(HIREDATE,4,2)=12;
--11. 다음과 같은 결과를 검색할 수 있는 SQL 문장을 작성하시오
--EMPNO		ENAME		급여
--7369		       SMITH		*******800
--7499		       ALLEN		******1600
--7521		       WARD		******1250
--……. 
SELECT EMPNO,ENAME,SAL FROM EMP;
SELECT EMPNO,ENAME,LPAD(SAL,10,'*') FROM EMP;
-- 12. 다음과 같은 결과를 검색할 수 있는 SQL 문장을 작성하시오
-- EMPNO	 ENAME 	입사일
-- 7369	  SMITH		1980-12-17
-- ….
SELECT EMPNO,ENAME,HIREDATE FROM EMP;
SELECT EMPNO,ENAME,TO_CHAR(HIREDATE,'YYYY-MM-DD') FROM EMP;
--13. 사원 테이블에서 부서 번호가 20인 사원의 사번, 이름, 직무, 급여를 출력하시오.
    --(급여는 앞에 $를 삽입하고3자리마다 ,를 출력한다)
SELECT EMPNO,ENAME,JOB,TO_CHAR(SAL,'$999,999') FROM EMP WHERE DEPTNO=20;