--Sub Query는 단일행 서브쿼리 ; 서브쿼리의 결과가 단일 행
--			단일 행 연산자 : =, >, >=, <, <=, <>
--	다중행 서브쿼리 ; 서브쿼리의 결과가 2행 이상의 행
--			복수 행 연산자 : IN, NOT IN, ANY, SOME, ALL, EXISTS

--SCOTT의 부서명 알기
SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT';
SELECT DNAME FROM DEPT WHERE DEPTNO=20;
SELECT DNAME FROM DEPT D,EMP E WHERE D.DEPTNO=E.DEPTNO AND ENAME='SCOTT';--이퀄 조인

--서브 쿼리 활용>>(서브쿼리)>>하나의 SQL 문장의 절 안에 포함된 또 하나의 SELECT 문장
SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT';--서브 쿼리
SELECT DNAME FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT');--메인 쿼리

--회사에서 급여를 가장 많이 받는 사람의 이름과 급여
SELECT MAX(SAL) FROM EMP;
SELECT ENAME FROM EMP WHERE SAL=5000;
SELECT ENAME FROM EMP WHERE SAL=(SELECT MAX(SAL) FROM EMP);

--SCOTT과 같은 부서에서 근무하는 사원의 이름과 부서번호를 출력
SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT';
SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO=20;
--서브쿼리 이용
SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT');

--SELF JOIN
SELECT E1.ENAME,E2.DEPTNO FROM EMP E1,EMP E2 WHERE E1.DEPTNO=E2.DEPTNO AND E2.ENAME='SCOTT';

--SCOTT과 같은 부서에서 근무하는 사원의 이름과 부서명을 출력
SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT';
SELECT ENAME,DNAME FROM DEPT D,EMP E WHERE D.DEPTNO=E.DEPTNO
                                    AND E.DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT');
--SELF JOIN
SELECT E2.ENAME,DNAME FROM EMP E1,EMP E2,DEPT D 
                                WHERE D.DEPTNO=E2.DEPTNO AND E1.DEPTNO=E2.DEPTNO AND E1.ENAME='SCOTT';
--SCOTT’와 같은 부서에 근무하는 사원들의 급여 총합을 출력
SELECT E2.DEPTNO,SUM(E2.SAL) FROM EMP E1,EMP E2 
                        WHERE E1.DEPTNO=E2.DEPTNO AND E1.ENAME='SCOTT' GROUP BY E2.DEPTNO;
SELECT SUM(SAL) FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT');
--?	‘SCOTT’과 같은 근무지에 근무하는 사원들의 이름
SELECT ENAME FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT');
--?	SCOTT과 동일한 JOB을 가진 사원의 모든 정보를 출력
SELECT * FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='SCOTT');
--?	SCOTT의 급여와 동일하거나 더 많이 받는 사원명과 급여를 출력
SELECT SAL FROM EMP WHERE ENAME='SCOTT';
SELECT ENAME,SAL FROM EMP WHERE SAL>=(SELECT SAL FROM EMP WHERE ENAME='SCOTT');_
--?	DALLAS에서 근무하는 사원의 이름, 부서번호를 출력
SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS';
SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS');
--?	SALES 부서에서 근무하는 모든 사원의 이름과 급여를 출력
SELECT ENAME,SAL FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');
--?	직속상관이 KING인 사원의 이름과 급여를 출력
SELECT * FROM EMP;
SELECT W.ENAME,W.SAL FROM EMP W,EMP M WHERE W.MGR=M.EMPNO AND M.ENAME='KING';
SELECT W.ENAME,W.SAL FROM EMP W,EMP M WHERE W.MGR=M.EMPNO AND 
                            M.EMPNO=(SELECT EMPNO FROM EMP WHERE ENAME='KING');
--?	사원들의 평균 급여 이하를 받는 사원의 사원번호와 이름, 급여를 출력
SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL<=(SELECT AVG(SAL) FROM EMP);
--?	SCOTT과 JOB이 같고, SCOTT과 부서번호가 같은 사람의 모든 정보를 출력
SELECT * FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='SCOTT');
SELECT * FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT');
SELECT * FROM EMP WHERE (JOB,DEPTNO)=(SELECT JOB,DEPTNO FROM EMP WHERE ENAME='SCOTT');